-- =====================================================================
-- LIFELINE ORACLE SCHEMA (ACTUAL)
-- =====================================================================

-- ----------------------------------------------------------------
-- USERS table
-- ----------------------------------------------------------------
CREATE TABLE USERS (
    ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EMAIL        VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    NAME         VARCHAR2(255 CHAR),
    ROLE         VARCHAR2(32 CHAR),
    PASSWORD     VARCHAR2(255 CHAR),
    IS_ACTIVE    NUMBER(1,0) DEFAULT 1 NOT NULL,
    IS_SUSPENDED NUMBER(1,0) DEFAULT 0 NOT NULL,
    DATE_JOINED  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------------
-- EMERGENCY_ALERTS table
-- ----------------------------------------------------------------
CREATE TABLE EMERGENCY_ALERTS (
    ID                        NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID                   NUMBER NOT NULL,
    EMERGENCY_IN_CHARGE_ID    NUMBER,
    MESSAGE                   CLOB,
    LATITUDE                  BINARY_DOUBLE,
    LONGITUDE                 BINARY_DOUBLE,
    ADDRESS                   VARCHAR2(500 CHAR),
    STATUS                    VARCHAR2(20 CHAR) DEFAULT 'pending' NOT NULL,
    CREATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ALERT_USER          FOREIGN KEY (USER_ID)
                                          REFERENCES USERS(ID),
    CONSTRAINT FK_ALERT_INCHARGE      FOREIGN KEY (EMERGENCY_IN_CHARGE_ID)
                                          REFERENCES USERS(ID)
);

COMMIT;
