-- =====================================================================
-- LIFELINE ORACLE SCHEMA (ACTUAL)
-- =====================================================================

-- ----------------------------------------------------------------
-- USERS table
-- ----------------------------------------------------------------
CREATE TABLE USERS (
    ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EMAIL        VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    NAME         VARCHAR2(255 CHAR),
    ROLE         VARCHAR2(32 CHAR),
    PASSWORD     VARCHAR2(255 CHAR),
    IS_ACTIVE    NUMBER(1,0) DEFAULT 1 NOT NULL,
    IS_SUSPENDED NUMBER(1,0) DEFAULT 0 NOT NULL,
    DATE_JOINED  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROFILE_PICTURE CLOB
);

-- ----------------------------------------------------------------
-- EMERGENCY_ALERTS table
-- ----------------------------------------------------------------
CREATE TABLE EMERGENCY_ALERTS (
    ID                        NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID                   NUMBER NOT NULL,
    EMERGENCY_IN_CHARGE_ID    NUMBER,
    MESSAGE                   CLOB,
    LATITUDE                  BINARY_DOUBLE,
    LONGITUDE                 BINARY_DOUBLE,
    ADDRESS                   VARCHAR2(500 CHAR),
    STATUS                    VARCHAR2(20 CHAR) DEFAULT 'pending' NOT NULL,
    CREATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ALERT_USER          FOREIGN KEY (USER_ID)
                                          REFERENCES USERS(ID),
    CONSTRAINT FK_ALERT_INCHARGE      FOREIGN KEY (EMERGENCY_IN_CHARGE_ID)
                                          REFERENCES USERS(ID)
);

-- ----------------------------------------------------------------
-- CLIENT_PROFILES table  (vehicle info + extra details per client)
-- ----------------------------------------------------------------
CREATE TABLE CLIENT_PROFILES (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER NOT NULL UNIQUE,
    PHONE            VARCHAR2(30 CHAR),
    INSURANCE_POLICY VARCHAR2(100 CHAR),
    VEHICLE_MAKE     VARCHAR2(80 CHAR),
    VEHICLE_MODEL    VARCHAR2(80 CHAR),
    VEHICLE_YEAR     VARCHAR2(10 CHAR),
    LICENSE_PLATE    VARCHAR2(20 CHAR),
    CONSTRAINT FK_CP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- ----------------------------------------------------------------
-- Sequences (required when using SEQUENCE strategy in JPA on Oracle)
-- ----------------------------------------------------------------
CREATE SEQUENCE USERS_SEQ               START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EMERGENCY_ALERTS_SEQ    START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CLIENT_PROFILES_SEQ     START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ----------------------------------------------------------------
-- Sample client account  (role = 'client', password = 'client123')
-- ----------------------------------------------------------------
INSERT INTO USERS (EMAIL, NAME, ROLE, PASSWORD, IS_ACTIVE, IS_SUSPENDED)
VALUES ('testclient@lifeline.com', 'Alex Martin', 'client', 'client123', 1, 0);

-- Add a sample vehicle profile for the test client
INSERT INTO CLIENT_PROFILES (USER_ID, PHONE, INSURANCE_POLICY, VEHICLE_MAKE, VEHICLE_MODEL, VEHICLE_YEAR, LICENSE_PLATE)
SELECT ID, '+1 (555) 000-1111', 'POL-2024-TEST-001', 'Toyota', 'Camry', '2022', 'LFN-9876'
FROM USERS
WHERE EMAIL = 'testclient@lifeline.com';

COMMIT;
